# Generated by Django 6.0.3 on 2026-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthuser',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthuser',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
