# Generated by Django 6.0.3 on 2026-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_healthuser_last_checkin_healthuser_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthuser',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthuser',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
