# Generated by Django 6.0.3 on 2026-06-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='foodentry',
            old_name='food_name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='macronutrients',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
